name: Node.JS CI/CD

on:
  push:
    branch: [testing]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install, build and test
        run: npm install
          npm test
          npm build
        with:
          node-version: ${{ matrix.node-version }}
